const express = require('express');
const path = require('path');
const router = require('./router');
const cookieParser = require('cookie-parser');
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(router);
console.log('start app');
module.exports = app;
